version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ticketing-app
    container_name: ticketing-app
    restart: unless-stopped
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: php artisan serve --host=0.0.0.0 --port=8000  
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_KEY: base64:ICxz1Fr8C2g6zD1iKncZut4br3/DKCLZShwVOpSzsPA=  
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ticketing
      DB_USERNAME: root
      DB_PASSWORD: root
    user: root
    networks:
      - ticketing-network

  db:
    image: mysql:8.0
    container_name: ticketing-db
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: ticketing
      MYSQL_ROOT_PASSWORD: root
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - ticketing-network

volumes:
  db_data:

networks:
  ticketing-network:
