version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ticketing-app
    container_name: ticketing-app
    restart: unless-stopped
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ticketing
      DB_USERNAME: root
      DB_PASSWORD: root
    user: root

  db:
    image: mysql:8.0
    container_name: ticketing-db
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3307"
    environment:
      MYSQL_DATABASE: ticketing
      MYSQL_ROOT_PASSWORD: root
    command: --default-authentication-plugin=mysql_native_password

volumes:
  db_data:
