version: '3.8'

services:
  app:
    build: .
    container_name: ticketing-app
    volumes:
      - .:/var/www
      - .env.docker:/var/www/.env
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:8.0
    container_name: ticketing-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ticketing
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
